env:
  - NODE_ENV=production

language: node_js
node_js:
  - 8
script:
  — yarn build
install:
  — npm install -g firebase-tools
after_success:
  — firebase deploy —-project=moodboard-b788b --token=$FIREBASE_TOKEN
